Oleksijt task15 user permision control without class
pivancy/programming_education pull request #68
Opened 2018-11-22 21:42 UTC by Oleksijt

Does this solution meet the requirements of the task?
Would it be better then previous solution?

2018-11-23 12:41 UTC, Oleksijt commented on oleksijt/users.py
> +class User:
Here - https://github.com/pivancy/programming_education/pull/68/commits/b71cbfda6dd6b3b78ff6728ef0a8e5142bc95e0f

2018-11-24 06:48 UTC, pivancy commented on oleksijt/users.py
> +""" This module contents functions and classes, that serve Users:
Why do we need this file here?

2018-11-24 07:00 UTC, Oleksijt commented on oleksijt/users.py
> +""" This module contents functions and classes, that serve Users:
I forgot to remove it.
Fixed.

2018-11-24 08:29 UTC, pivancy commented on oleksijt/users_without_class.py
> +    def wrapper(name):
Why do not write something like that?

    def access_control(fn):
        def wrapped(*args, **kwargs):
            if get_user() != admin_name:
                raise PermissionException("Permission denied.")
            return fn(*args, **kwargs)
        return wrapped

2018-11-24 21:44 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +    def wrapper(name):
Done.
When should i use Try: Except:?

2018-11-25 08:52 UTC, pivancy commented on oleksijt/users_without_class.py
> +    def wrapper(name):
You don't need try except here.

2018-11-25 10:48 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +    def wrapper(name):
Ok. I did it without "except".
But can you explain in what cases i need it?

2018-11-28 14:09 UTC, pivancy commented on oleksijt/users_without_class.py
> +    def wrapper(name):
This functionality is super useful for the platforms with limited access for different groups of users.

2018-11-28 14:42 UTC, pivancy commented on oleksijt/users_without_class.py
> +    def wrapper(name):
It would be great to make this decorator possible to use in this way:

2018-11-28 20:32 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +    def wrapper(name):
Done.

2018-11-28 21:12 UTC, pivancy commented on oleksijt/users_without_class.py
> +    print(check_perms('Yuriy'))  # Prints `Permission denied.`
Why this returns Permission denied if Yuriy is in moderators list?

2018-11-29 06:55 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +    print(check_perms('Yuriy'))  # Prints `Permission denied.`
Fixed.

2018-11-29 21:37 UTC, UkrainianEngineer requested changes

2018-11-29 21:37 UTC, pivancy commented on oleksijt/users_without_class.py
> +@allowed_users(admins_list + moderators_list)
It's not a good idea for adding two lists in this way.

2018-11-29 21:37 UTC, pivancy commented on oleksijt/users_without_class.py
> +                raise PermissionError('Permission denied.')
I suggest you to rename it to `PermissionDenied` and define this custom Exception to avoid a `NameError`.

2018-11-30 18:56 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +@allowed_users(admins_list + moderators_list)
Fixed. Now it ads only unique values.

2018-11-30 21:55 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +                raise PermissionError('Permission denied.')
Done.

2018-12-03 21:36 UTC, pivancy commented on oleksijt/users_without_class.py
> +        print('Permission denied.')
I don't think you really need to handle it here, but ok.

2018-12-03 21:36 UTC, UkrainianEngineer approved these changes

2018-12-03 21:36 UTC, pivancy commented
👍

2018-12-04 17:17 UTC, Oleksijt commented on oleksijt/users_without_class.py
> +        print('Permission denied.')
I've handled it to see further testing result without error.

2018-12-04 17:17 UTC, merged